# Generated by Django 5.1.6 on 2025-03-07 11:04

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("mother_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "m"), ("f", "f")], default="m", max_length=5
                    ),
                ),
                ("birth", models.DateField(default="2000-1-1")),
                (
                    "photo",
                    models.ImageField(
                        default="users/photos/default.png",
                        null=True,
                        upload_to="users/photos",
                    ),
                ),
                ("token", models.CharField(default="", max_length=65, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("no_judgment", models.ImageField(upload_to="users/no_judgment")),
                ("id_image_front", models.ImageField(upload_to="users/id_img_front")),
                ("id_image_back", models.ImageField(upload_to="users/id_img_back")),
                (
                    "residence_permit",
                    models.ImageField(upload_to="users/residence_permit"),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
