# Generated by Django 5.1.6 on 2025-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('مستقل - فئة - أ', 'مستقل - فئة - أ'), ('مستقل - فئة - ب', 'مستقل - فئة - ب'), ('حزبي', 'حزبي')], default='مستقل - فئة - أ', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='electoral_program',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(choices=[('دمشق', 'دمشق'), ('حلب', 'حلب'), ('إدلب', 'إدلب'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس'), ('بانياس', 'بانياس'), ('حماة', 'حماة'), ('حمص', 'حمص'), ('الحسكة', 'الحسكة'), ('الرقة', 'الرقة'), ('القامشلي', 'القامشلي'), ('درعا', 'درعا'), ('السويداء', 'السويداء'), ('القنيطرة', 'القنيطرة')], default='دمشق', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_image_back',
            field=models.ImageField(default='users/id_img_back/default.png', null=True, upload_to='users/id_img_back/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_image_front',
            field=models.ImageField(default='users/id_img_front/default.png', null=True, upload_to='users/id_img_front/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_judgment',
            field=models.ImageField(default='users/no_judgment/default.png', null=True, upload_to='users/no_judgment/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users/photos/default.png', null=True, upload_to='users/photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence_permit',
            field=models.ImageField(default='users/residence_permit/default.png', null=True, upload_to='users/residence_permit/'),
        ),
    ]
