# Generated by Django 5.1.6 on 2025-05-16 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_category_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acadime_digree',
            field=models.CharField(choices=[('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه'), ('دبلوم', 'دبلوم'), ('دبلوم عالي', 'دبلوم عالي'), ('زمالة', 'زمالة'), ('ثانوية عامة', 'ثانوية عامة'), ('غير ذلك', 'غير ذلك')], default='غير ذلك', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='essay',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='video',
            field=models.ImageField(null=True, upload_to='users/videos/'),
        ),
    ]
