# Generated by Django 5.1.6 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_acadime_digree_user_education_user_essay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.FileField(null=True, upload_to='users/videos/'),
        ),
    ]
