# Generated by Django 5.1.6 on 2025-05-16 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='video_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='essay',
            field=models.FileField(null=True, upload_to='users/essay/'),
        ),
    ]
